### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by Dino-Kupinic** [Dino-Kupinic/UntisPlanner#2]
a navbar that works on desktop and mobile

includes:
- Untis Planner Logo
- Light/Dark mode switch
- Settings Button
- Info Button (#18)

**Comment by Vishnudas2003** [comment]
### Overview
I'm excited to work on implementing Navbar #2 for the Untis Planner project. Here's the plan for the navbar, which will work seamlessly on both desktop and mobile devices.

Looking forward to contributing to the project! 🚀

**Comment by Vishnudas2003** [comment]
Hello, I am not able to push the change, its showing 
![image](https://github.com/Dino-Kupinic/UntisPlanner/assets/94338168/92cb858a-9db7-4a27-85c7-63632bebd920)
